remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: "RAG-HAR: Retrieval Augmented Generation-based Human Activity Recognition"
description:
baseurl: ""
url: "https://rag-har-llm.github.io"
